server:
  port: 9007
spring:
  application:
    name: ccdn_search
  data:
    elasticsearch:
      cluster-nodes: 123.56.120.185:9300
      cluster-name:  my-application
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true