server:
  port: 6868
spring:
  application:
    name: ccdn-eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/