server: 
  port: 9003
spring: 
  application:  
    name: ccdn-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.120.185:3306/ccdn_qa?characterEncoding=UTF8
    username: root
    password: 12345678
  jpa: 
    database: MySQL
    show-sql: true
