server:
  port: 9006
spring:
  application:
    name: ccdn-spit
  data:
    mongodb:
      host: 123.56.120.185
      database: spitdb
  redis:
    host: 123.56.120.185
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true