server: 
  port: 9004
spring: 
  application:  
    name: ccdn-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.120.185:3306/ccdn_article?characterEncoding=UTF8
    username: root
    password: 12345678
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 123.56.120.185
    port: 6379
